#!/usr/bin/env python3
"""Build the complete English WRRA Game 1.0 technical report."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import matplotlib.pyplot as plt
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt

import wrra_game_0_1 as game01
from build_wrra_game_0_2_report import (
    MATH_FONT,
    configure_document,
    draw_go_board,
    equation,
    figure,
    heading,
    numbered,
    paragraph,
    set_cell_margins,
    set_font,
    table,
)


ROOT = Path(__file__).resolve().parent
OUT = ROOT / "wrra_game_output" / "v1_0_en"
DOCX_PATH = ROOT / "WRRA_Game_1.0_Minimal_Sufficient_State_and_a_Playable_Go_Engine_Wonsik_Choi_2026-09-17.docx"
R01_PATH = ROOT / "wrra_game_output" / "wrra_game_0_1_results.json"
R02_PATH = ROOT / "wrra_game_output" / "wrra_game_0_2_results.json"
BENCH_PATH = ROOT / "wrra_go_output" / "wrra_go_0_1_benchmark.json"
TEST_PATH = ROOT / "wrra_go_output" / "wrra_go_0_1_rule_tests.json"
SELFPLAY_PATH = ROOT / "wrra_go_output" / "wrra_go_0_1_selfplay_9x9.json"

BLUE = "#3C78A8"
GREEN = "#2E7D5B"


def file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def compact_table(tbl, font_size=8.25, margin=72):
    """Tighten a dense table without changing its content."""
    header = tbl.rows[0]
    for row in tbl.rows:
        for cell in row.cells:
            set_cell_margins(cell, top=margin, start=90, bottom=margin, end=90)
            for p in cell.paragraphs:
                for run in p.runs:
                    set_font(run, font_size, bold=run.bold, color="FFFFFF" if row is header else None)
    return tbl


def render_equation(tex: str, filename: str, width=10.0, height=0.75, fontsize=18) -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / filename
    fig = plt.figure(figsize=(width, height), facecolor="white")
    fig.text(0.5, 0.5, f"${tex}$", ha="center", va="center", fontsize=fontsize, fontfamily=MATH_FONT)
    fig.savefig(path, dpi=260, bbox_inches="tight", pad_inches=0.08, facecolor="white")
    plt.close(fig)
    return path


def create_figures(r02: dict, benchmark: dict, selfplay: dict) -> dict[str, Path]:
    OUT.mkdir(parents=True, exist_ok=True)
    ck = r02["connect_k"]
    go = r02["go"]

    omok_path = OUT / "figure_omok_fork_en.png"
    omok = game01.omok_constructive_state()
    move = (4, 4)
    after = omok.play(move)
    outlets = omok.threat_outlets(move, game01.BLACK)
    fig, axes = plt.subplots(1, 2, figsize=(9.6, 4.8), constrained_layout=True, facecolor="white")
    game01.draw_board(omok.board, axes[0], "Before the central move", {move: ("M", "#D62728")})
    markers = {point: ("T", "#1F77B4") for point in outlets}
    markers[move] = ("M", "#D62728")
    game01.draw_board(after.board, axes[1], "Four next-turn winning outlets", markers)
    fig.suptitle("A multiple-threat phenotype generated by local rules", fontsize=14, fontweight="bold")
    fig.savefig(omok_path, dpi=240, facecolor="white")
    plt.close(fig)

    ko_path = OUT / "figure_go_ko_en.png"
    before = game01.go_ko_state("simple")
    result = before.play((2, 3))
    fig, axes = plt.subplots(1, 2, figsize=(8.8, 4.4), constrained_layout=True, facecolor="white")
    game01.draw_board(before.board, axes[0], "Before capture", {(2, 3): ("M", "#D62728")})
    game01.draw_board(result.state.board, axes[1], "After capture: ko residue active", {(2, 2): ("K", "#9467BD")})
    fig.suptitle("One update creates both a capture and a repetition constraint", fontsize=14, fontweight="bold")
    fig.savefig(ko_path, dpi=240, facecolor="white")
    plt.close(fig)

    search_path = OUT / "figure_connect_search_en.png"
    labels = ["Baseline order", "Renderer order", "Certified reduction"]
    values = [
        ck["root_alpha_beta"]["baseline"]["nodes"],
        ck["root_alpha_beta"]["renderer_order"]["nodes"],
        ck["root_alpha_beta"]["renderer_gate"]["nodes"],
    ]
    fig, ax = plt.subplots(figsize=(8.0, 4.2), facecolor="white")
    bars = ax.bar(labels, values, color=["#7B8794", BLUE, GREEN], width=0.62)
    ax.set_yscale("log")
    ax.set_ylabel("Search nodes (log scale)")
    ax.set_title("Search required for the same exact root value")
    ax.grid(axis="y", color="#D9D9D9", linewidth=0.7)
    ax.set_axisbelow(True)
    for bar, value in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2, value * 1.25, f"{value:,}", ha="center", fontsize=10)
    fig.tight_layout()
    fig.savefig(search_path, dpi=240, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    residue_path = OUT / "figure_go_residue_counts_en.png"
    labels = ["Visible-state classes", "Multiple residues", "Different legal sets"]
    values = [
        go["unique_visible_state_classes"],
        go["classes_with_multiple_reachable_residues"],
        go["classes_with_residue_dependent_legal_actions"],
    ]
    fig, ax = plt.subplots(figsize=(8.0, 4.1), facecolor="white")
    bars = ax.barh(labels[::-1], values[::-1], color=["#B3212D", BLUE, "#7B8794"])
    ax.set_xscale("log")
    ax.set_xlabel("Number of equivalence classes (log scale)")
    ax.set_title("Same visible state, different reachable residues")
    ax.grid(axis="x", color="#D9D9D9", linewidth=0.7)
    ax.set_axisbelow(True)
    for bar, value in zip(bars, values[::-1]):
        ax.text(value * 1.10, bar.get_y() + bar.get_height() / 2, f"{value:,}", va="center", fontsize=10)
    fig.tight_layout()
    fig.savefig(residue_path, dpi=240, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    witness = go["witness"]
    witness_path = OUT / "figure_go_witness_en.png"
    fig, axes = plt.subplots(1, 3, figsize=(10.5, 3.5), facecolor="white")
    draw_go_board(axes[0], witness["board_rows"], "Same current board", witness["differing_action"])
    draw_go_board(axes[1], witness["legal_previous_board_rows"], "History A: legal")
    draw_go_board(axes[2], witness["blocked_previous_board_rows"], "History B: blocked by ko")
    fig.suptitle("The legality of White (0, 1) is not determined by the current board alone", fontsize=13, fontweight="bold", y=1.02)
    fig.tight_layout()
    fig.savefig(witness_path, dpi=240, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    architecture_path = OUT / "figure_wrra_go_architecture_en.png"
    fig, ax = plt.subplots(figsize=(10.5, 3.8), facecolor="white")
    ax.set_xlim(0, 10.5)
    ax.set_ylim(0, 3.8)
    ax.axis("off")
    boxes = [
        (0.25, "Complete state\nboard, turn, residue, passes", "#E9EEF3"),
        (2.35, "Legal transition\ncapture, suicide, ko", "#E7F1EA"),
        (4.45, "Renderer\n11 transparent channels", "#E7EEF6"),
        (6.55, "MCTS\nevaluate allowed branches", "#F6EFE3"),
        (8.65, "Move + ledger\nrecord the rationale", "#F4E8EA"),
    ]
    for x, label, colour in boxes:
        patch = plt.Rectangle((x, 1.15), 1.6, 1.25, facecolor=colour, edgecolor="#66717C", linewidth=1.2)
        ax.add_patch(patch)
        ax.text(x + 0.8, 1.77, label, ha="center", va="center", fontsize=9.6, fontweight="bold")
    for x in (1.88, 3.98, 6.08, 8.18):
        ax.annotate("", xy=(x + 0.38, 1.77), xytext=(x, 1.77), arrowprops=dict(arrowstyle="->", color="#24364B", lw=1.8))
    ax.text(5.25, 3.12, "How WRRA Go 0.1 selects one move", ha="center", fontsize=14, fontweight="bold")
    ax.text(5.25, 0.55, "Search generates and evaluates rule-permitted successors; it does not observe a pre-existing future.", ha="center", fontsize=10)
    fig.tight_layout()
    fig.savefig(architecture_path, dpi=240, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    bench_path = OUT / "figure_wrra_go_benchmark_en.png"
    summaries = [benchmark["summary"]["uniform_mcts"], benchmark["summary"]["random"]]
    labels = ["Uniform MCTS\nsame budget", "Random legal move"]
    rates = [item["wrra_win_rate"] for item in summaries]
    lower = [rate - item["wilson_95_interval"][0] for rate, item in zip(rates, summaries)]
    upper = [item["wilson_95_interval"][1] - rate for rate, item in zip(rates, summaries)]
    fig, ax = plt.subplots(figsize=(7.8, 4.6), facecolor="white")
    bars = ax.bar(labels, rates, color=[BLUE, GREEN], width=0.58, yerr=[lower, upper], capsize=7)
    ax.set_ylim(0, 1.08)
    ax.set_ylabel("WRRA MCTS win rate")
    ax.set_title(f"{benchmark['rules']['board']} paired-colour matches; {summaries[0]['games']} games per control")
    ax.grid(axis="y", color="#D9D9D9", linewidth=0.7)
    ax.set_axisbelow(True)
    for bar, rate, item in zip(bars, rates, summaries):
        ax.text(bar.get_x() + bar.get_width() / 2, min(1.035, rate + 0.035), f"{item['wrra_wins']} / {item['games']}", ha="center", fontsize=11, fontweight="bold")
    fig.tight_layout()
    fig.savefig(bench_path, dpi=240, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    final_path = OUT / "figure_wrra_go_selfplay_final_en.png"
    fig, ax = plt.subplots(figsize=(5.5, 5.5), facecolor="white")
    draw_go_board(ax, selfplay["final_board"], "Final position of the 9×9 WRRA self-play game")
    fig.tight_layout()
    fig.savefig(final_path, dpi=240, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    candidate_path = OUT / "figure_wrra_go_first_move_en.png"
    first = selfplay["moves"][0]["decision"]["candidates"][:8]
    labels = [item["action"] for item in first]
    visits = [item["visits"] for item in first]
    fig, ax = plt.subplots(figsize=(8.0, 4.2), facecolor="white")
    bars = ax.bar(labels, visits, color=[GREEN if i == 0 else "#AAB2BA" for i in range(len(first))])
    ax.set_ylabel("MCTS visits")
    ax.set_title("Candidate ledger for the first 9×9 self-play move")
    ax.grid(axis="y", color="#D9D9D9", linewidth=0.7)
    ax.set_axisbelow(True)
    for bar, value in zip(bars, visits):
        ax.text(bar.get_x() + bar.get_width() / 2, value + 0.2, str(value), ha="center", fontsize=9)
    fig.tight_layout()
    fig.savefig(candidate_path, dpi=240, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    return {
        "omok": omok_path,
        "ko": ko_path,
        "search": search_path,
        "residue": residue_path,
        "witness": witness_path,
        "architecture": architecture_path,
        "benchmark": bench_path,
        "final": final_path,
        "candidates": candidate_path,
    }


def add_cover(doc: Document) -> None:
    p = doc.add_paragraph(style="Title")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(48)
    set_font(p.add_run("WRRA Game 1.0"), 25, True)
    p = paragraph(doc, "Minimal Sufficient State for Complex Games and a Playable Go Engine", align=WD_ALIGN_PARAGRAPH.CENTER, size=16)
    p.paragraph_format.space_after = Pt(12)
    p = paragraph(doc, "Constructive Omok and Go Analysis, Exhaustive Validation, and WRRA Go 0.1", align=WD_ALIGN_PARAGRAPH.CENTER, size=12)
    p.paragraph_format.space_after = Pt(32)
    paragraph(doc, "Wonsik Choi", align=WD_ALIGN_PARAGRAPH.CENTER, size=12)
    paragraph(doc, "Independent Researcher", align=WD_ALIGN_PARAGRAPH.CENTER, size=10.5)
    paragraph(doc, "janefather@gmail.com", align=WD_ALIGN_PARAGRAPH.CENTER, size=11)
    paragraph(doc, "17 September 2026", align=WD_ALIGN_PARAGRAPH.CENTER, size=11)
    p = paragraph(doc, "WRRA Core 1.0 remains frozen", align=WD_ALIGN_PARAGRAPH.CENTER, size=10)
    p.paragraph_format.space_before = Pt(28)
    paragraph(doc, "Integrated technical report and reproducibility archive", align=WD_ALIGN_PARAGRAPH.CENTER, size=10)
    doc.add_page_break()


def build() -> None:
    r01 = json.loads(R01_PATH.read_text(encoding="utf-8"))
    r02 = json.loads(R02_PATH.read_text(encoding="utf-8"))
    benchmark = json.loads(BENCH_PATH.read_text(encoding="utf-8"))
    tests = json.loads(TEST_PATH.read_text(encoding="utf-8"))
    selfplay = json.loads(SELFPLAY_PATH.read_text(encoding="utf-8"))
    ck = r02["connect_k"]
    go = r02["go"]
    uniform = benchmark["summary"]["uniform_mcts"]
    random_control = benchmark["summary"]["random"]
    winner_name = {"B": "Black", "W": "White"}.get(selfplay["winner"], selfplay["winner"])
    ending_name = {"two_passes": "two consecutive passes"}.get(selfplay["ended_by"], selfplay["ended_by"])
    figures = create_figures(r02, benchmark, selfplay)

    eq_suff = render_equation(r"M(h_1)=M(h_2)\Rightarrow A_{legal}(h_1)=A_{legal}(h_2)", "eq_suff_en.png", width=9.4)
    eq_state = render_equation(r"S_t=(B_t,p_t,\rho_t,c_t,n_t),\qquad \rho_t=B_{t-1}", "eq_state_en.png", width=8.5)
    eq_update = render_equation(r"T(S_t,a)=S_{t+1}\quad\text{iff}\quad a\in A_{legal}(S_t;L_D,\rho_t)", "eq_update_en.png", width=10.0)
    eq_renderer = render_equation(r"R(a\mid S)=\sum_{i=1}^{11}w_i f_i(S,a)", "eq_renderer_en.png", width=7.2)
    eq_puct = render_equation(r"a^*=\arg\max_a\left(Q(S,a)+c\,P_R(a\mid S)\frac{\sqrt{N(S)}}{1+N(S,a)}\right)", "eq_puct_en.png", width=11.0)
    eq_lossless = render_equation(r"\sum_{S\in\mathcal{S}_{reach}}\mathbf{1}[V_{base}(S)\ne V_{WRRA}(S)]=0", "eq_lossless_en.png", width=9.5)

    doc = Document()
    configure_document(doc)
    add_cover(doc)

    heading(doc, "Abstract", 1)
    paragraph(doc,
        "WRRA Game 1.0 connects three levels of evidence under one unchanged execution contract. WRRA Game 0.1 computes a constructive forced-win phenotype in 9×9 freestyle Omok and a simple-ko counterexample in 5×5 Go. WRRA Game 0.2 exhaustively enumerates 6,036,001 reachable states of a 4×4 Connect-K system and 132,161 reachable complete states of 3×3 Go. The certified Renderer reduction has zero minimax-value mismatches over the entire Connect-K reachability graph, while 752 visible-state equivalence classes in Go have legal-action sets that depend on previous-board residue. WRRA Go 0.1 then reuses the verified Go transition system in a playable 9×9 engine, combining an explicit eleven-channel Renderer with Monte Carlo Tree Search and an auditable decision ledger.")
    paragraph(doc,
        "The central methodological claim is precise: a game agent should preserve the minimum state required for exact legality and state update, then spend bounded computation on structurally informative legal continuations. Residue does not predict or preserve the future. It carries present constraint information that is absent from the visible board. Search generates and compares successor states permitted by the current rules. The archive includes source code, deterministic rule tests, exhaustive-search ledgers, paired-colour control matches, and a complete SGF self-play record.")
    paragraph(doc, "Keywords: WRRA; Go; Baduk; Omok; Connect K; MCTS; minimal sufficient state; residue; Renderer; exhaustive search; explainable game AI; complex systems.")

    heading(doc, "Executive result", 1)
    table(doc, ["Stage", "Question", "Executed evidence", "Established meaning"], [
        ["Game 0.1", "Can the structure compute concrete cases?", "70 Omok replies; one ko counterexample", "Constructive operation"],
        ["Game 0.2", "Are value and legality preserved globally?", "6,036,001 Connect-K states; 132,161 Go states", "Exhaustive finite validation"],
        ["Game 1.0", "Can the same structure select actual moves?", "Playable 9×9 engine and paired controls", "Transition from analysis to action"],
    ], [1.05, 1.75, 2.35, 1.45], center_cols=(0,))
    table(doc, ["Domain", "Scope", "Result", "Interpretation"], [
        ["Connect K", f"{ck['reachable_full_states']:,} reachable states", f"{ck['all_state_value_mismatches']:,} minimax mismatches", "Certified reduction preserves value"],
        ["Connect K", "Empty-board alpha-beta", f"{ck['root_alpha_beta']['baseline']['nodes']:,} → {ck['root_alpha_beta']['renderer_gate']['nodes']:,} nodes", "Same exact root value"],
        ["3×3 Go", f"{go['reachable_full_states']:,} complete states", f"{go['classes_with_residue_dependent_legal_actions']:,} residue-dependent classes", "Board alone is insufficient"],
        ["WRRA Go", f"{uniform['games']} games vs uniform MCTS", f"{uniform['wrra_wins']}–{uniform['wrra_losses']}", "Equal simulation budget"],
        ["WRRA Go", f"{random_control['games']} games vs random", f"{random_control['wrra_wins']}–{random_control['wrra_losses']}", "Alternating colours"],
        ["9×9 self-play", f"{selfplay['move_count']} moves", f"{winner_name} wins; Black margin {selfplay['score']['black_margin']:+.1f}", ending_name],
    ], [1.25, 1.85, 2.05, 1.7], center_cols=(0, 1, 2))
    paragraph(doc,
        "These match results are an action-selection evaluation, not a claim of professional Go strength. Their importance is that the same explicit legality, residue, transition, Renderer, and ledger structure runs end to end and can be compared with controls under equal computational budgets.")

    heading(doc, "Contents", 2)
    numbered(doc, [
        "The common WRRA execution contract and exact terminology",
        "WRRA Game 0.1: constructive Omok and Go analyses",
        "WRRA Game 0.2: exhaustive validation",
        "WRRA Go 0.1: a playable action-selection algorithm",
        "Execution tests, paired controls, and 9×9 self-play",
        "Scientific value, limits, and generalization",
        "Reproducibility, file manifest, and release metadata",
    ])

    doc.add_page_break()
    heading(doc, "1. Common execution contract", 1)
    heading(doc, "1.1 A domain profile, not a modification of WRRA Core 1.0", 2)
    paragraph(doc,
        "The game work is a domain profile, not a revision of WRRA Core 1.0. The frozen Core fixes the execution order—SOURCE, LAW, STATE and RESIDUE, BOUNDARY, COMMON CARRIER, UPDATE, RENDERER, PHENOTYPE, and LEDGER—while each game's rules and objectives remain in its profile. Omok and Go keep their real differences but face the same diagnostic questions.")
    core_tbl = table(doc, ["Core item", "Omok / Connect K", "Go", "Playable Go engine"], [
        ["SOURCE", "Placement on an empty point", "Placement or pass", "Human or algorithmic action"],
        ["LAW", "Alternation and K-in-a-row", "Liberty, capture, suicide, simple ko", "Executable rule functions"],
        ["STATE", "Board and side to move", "Board, turn, residue, pass count", "Adds move index and tree nodes"],
        ["RESIDUE", "No additional history", "One previous board", "Used directly for ko legality"],
        ["BOUNDARY", "Empty points and winning lines", "Boundary of legal placements", "Only legal candidates are searched"],
        ["CARRIER", "Finite grid", "Finite orthogonal grid", "Shared coordinates and occupancy"],
        ["UPDATE", "Place and alternate", "Capture, ko test, then alternate", "Immutable GoState result"],
        ["RENDERER", "Win threats and forced blocks", "Capture, liberty, connection, cut", "Prior and rollout ordering"],
        ["PHENOTYPE", "Win, forced loss, open search", "Capture, rescue, atari, and others", "Human-readable move label"],
        ["LEDGER", "State values and nodes", "Legal sets and witness histories", "Visits, values, features, record"],
    ], [1.05, 1.75, 1.85, 1.95], center_cols=(0,))
    compact_table(core_tbl, 8.35, 66)

    heading(doc, "1.2 State sufficiency", 2)
    paragraph(doc,
        "A state representation M is sufficient only if two legal histories compressed to the same M admit the same legal actions and compatible next-state updates. If identical visible boards permit different actions because of history, M omits information required by the current computation. This is the criterion for adding residue; it is not a reason to store the entire past indiscriminately.")
    equation(doc, eq_suff, 5.5)
    paragraph(doc,
        "Freestyle Omok needs the board and side to move. Go with simple ko additionally needs one previous board to reject immediate repetition. If the selected law uses positional superko, residue must grow to encode the longer repetition constraint. The law, not preference, determines the minimum memory.")

    heading(doc, "1.3 Interpretation, search, and prediction", 2)
    table(doc, ["Term", "Meaning in this work", "Meaning explicitly excluded"], [
        ["State transition", "Compute a next state after a legal action", "Observe reality's future in advance"],
        ["Successor branch", "A candidate generated under current rules", "An event that must actually occur"],
        ["Search", "Compare candidate states under an objective", "Automatic empirical prediction"],
        ["Residue", "Current constraint information needed for legality", "Storage of the future itself"],
        ["Renderer score", "Structural features and search priority", "An unconditional prophecy of the game result"],
    ], [1.25, 2.65, 2.7], center_cols=(0,))
    paragraph(doc,
        "Accordingly, this report replaces earlier phrases such as ‘preserving future branches.’ The exact statement is: residue preserves the information needed to compute legal actions and exact state updates; Renderer-guided search generates and evaluates rule-permitted successors.")

    doc.add_page_break()
    heading(doc, "2. WRRA Game 0.1: constructive analysis", 1)
    heading(doc, "2.1 A forced-win outlet in 9×9 freestyle Omok", 2)
    o1 = r01["omok"]
    paragraph(doc,
        "Game 0.1 evaluates every one of 71 legal candidates in a specified 9×9 position. Only the central move (4, 4) creates four immediate winning outlets for Black's following turn. All 70 legal White replies were then applied; none removed all four outlets. This is a constructive case in which a Renderer exposes a living boundary and a multiple-threat phenotype before deeper search.")
    figure(doc, figures["omok"], "Figure 1. The central Omok move creates four next-turn winning outlets.", 6.3)
    table(doc, ["Item", "Value", "Meaning"], [
        ["Legal candidates", o1["legal_move_count"], "All empty points"],
        ["Multiple-outlet candidates", o1["fork_candidate_count"], "Only the central move"],
        ["Winning outlets created", o1["outlet_count"], "Four endpoints on two lines"],
        ["Defensive replies tested", o1["defensive_replies_checked"], "Every legal White response"],
        ["Replies removing all outlets", o1["defensive_replies_escaping_all_immediate_wins"], "Forced-win certificate"],
        ["Candidate reduction", f"{100 * o1['candidate_reduction_fraction']:.2f}%", "Constructive Renderer example"],
    ], [2.05, 1.45, 3.1], center_cols=(1,))

    heading(doc, "2.2 Simple ko and residue in 5×5 Go", 2)
    g1 = r01["go"]
    paragraph(doc,
        "The Go example constructs a direct counterexample to board-only state. A capture removes one White stone. Immediate recapture would reproduce the previous board and is illegal under simple ko. With previous-board residue the position has 18 legal actions; without it the forbidden recapture enters the set, producing 19.")
    figure(doc, figures["ko"], "Figure 2. Previous-board residue blocks an immediate ko recapture.", 6.1)
    table(doc, ["Test", "With residue", "Without residue", "Judgment"], [
        ["Immediate recapture", "Illegal", "Legal", "The latter restores the prior board"],
        ["Number of legal actions", g1["legal_actions_with_residue"], g1["legal_actions_without_residue"], "One-action difference"],
    ], [1.55, 1.55, 1.55, 2.1], center_cols=(0, 1, 2))
    paragraph(doc,
        "Game 0.1 therefore ties two abstract terms to executable cases. Renderer exposes live threats and boundaries so that candidates can be ranked or safely reduced. Residue attaches a legal constraint that is absent from the current board. Game 0.2 asks whether these observations remain valid over complete reachability graphs.")

    doc.add_page_break()
    heading(doc, "3. WRRA Game 0.2: exhaustive validation", 1)
    heading(doc, "3.1 The 4×4, three-in-a-row Connect-K system", 2)
    paragraph(doc,
        "Instead of claiming exhaustive coverage of standard 15×15 Omok, the experiment uses a fully enumerable system: a 4×4 board where three in a row wins. Starting from the empty board, it closes only states reachable under alternation and early termination. The question is not playing strength on a small board. It is whether a certified Renderer reduction changes the exact minimax value at any reachable state.")
    table(doc, ["Ledger item", "Value", "Ledger item", "Value"], [
        ["Reachable states", f"{ck['reachable_full_states']:,}", "Directed legal edges", f"{ck['directed_legal_edges']:,}"],
        ["Terminal wins", f"{ck['terminal_win_states']:,}", "Terminal draws", f"{ck['terminal_draw_states']:,}"],
        ["Immediate-win states", f"{ck['phenotype_census']['immediate_win']:,}", "Single mandatory blocks", f"{ck['phenotype_census']['mandatory_block']:,}"],
        ["Multiple-threat forced losses", f"{ck['phenotype_census']['forced_loss_certificate']:,}", "Open-search states", f"{ck['phenotype_census']['open_search']:,}"],
        ["All-state value mismatches", f"{ck['all_state_value_mismatches']:,}", "Empty-board value", ck["root_exact_value"]],
    ], [1.8, 1.2, 1.85, 1.15], center_cols=(1, 3))
    equation(doc, eq_lossless, 5.75)
    paragraph(doc,
        "The reduction keeps only an immediate winning move when one exists; keeps the unique block when the opponent has exactly one immediate winning point; and issues a forced-loss certificate when two distinct winning points cannot both be blocked by one move. In every other state it discards nothing and changes only move order. Comparison with baseline minimax over all 6,036,001 reachable states yields zero value mismatches.")
    figure(doc, figures["search"], "Figure 3. Alpha-beta nodes needed to recover the same exact empty-board value.", 6.15)
    table(doc, ["Search", "Visited nodes", "Reduction from baseline", "Root value"], [
        ["Baseline row-major", f"{ck['root_alpha_beta']['baseline']['nodes']:,}", "0%", ck["root_alpha_beta"]["baseline"]["value"]],
        ["Renderer ordering", f"{ck['root_alpha_beta']['renderer_order']['nodes']:,}", f"{100 * ck['node_reduction_vs_baseline']['renderer_order_fraction']:.3f}%", ck["root_alpha_beta"]["renderer_order"]["value"]],
        ["Certified Renderer reduction", f"{ck['root_alpha_beta']['renderer_gate']['nodes']:,}", f"{100 * ck['node_reduction_vs_baseline']['renderer_gate_fraction']:.5f}%", ck["root_alpha_beta"]["renderer_gate"]["value"]],
    ], [2.25, 1.35, 1.75, 1.05], center_cols=(1, 2, 3))

    heading(doc, "3.2 The complete reachable graph of 3×3 simple-ko Go", 2)
    paragraph(doc,
        "The Go system implements capture, suicide prohibition, simple ko, pass, and termination after two consecutive passes. A complete state contains the current board, side to move, previous-board residue, and consecutive-pass count. States with the same current board, player, and pass count are grouped; the analysis then asks whether changing only the reachable residue changes the set of legal placements.")
    figure(doc, figures["residue"], "Figure 4. Visible-state classes in which reachable residues and legal sets differ.", 6.1)
    table(doc, ["Class", "Count", "Meaning"], [
        ["Complete states", f"{go['reachable_full_states']:,}", "Reachable states including residue"],
        ["Directed legal edges", f"{go['directed_legal_edges']:,}", "Placements and passes"],
        ["Visible-state classes", f"{go['unique_visible_state_classes']:,}", "Same board, player, and pass count"],
        ["Classes with multiple residues", f"{go['classes_with_multiple_reachable_residues']:,}", "Different previous boards"],
        ["Classes with different legal sets", f"{go['classes_with_residue_dependent_legal_actions']:,}", "Residue alone changes legality"],
        ["Ko-sensitive complete states", f"{go['ko_sensitive_full_states']:,}", "Exactly one placement is blocked"],
        ["Maximum distinct legal sets", f"{go['max_distinct_legal_action_sets_per_visible_state']:,}", "For one visible-state class"],
    ], [2.35, 1.25, 3.0], center_cols=(1,))
    figure(doc, figures["witness"], "Figure 5. A shortest five-move witness pair: the same current board, different legality at White (0, 1).", 6.4)
    paragraph(doc,
        "This is not a result about predictive accuracy. It is a result about the information that must be present to decide whether an action is legal now. The two shortest witness histories reach the same board with the same player to move after five moves, yet White (0, 1) is legal in one state and forbidden in the other because it would recreate the latter state's previous board.")

    heading(doc, "3.3 Design rules extracted from exhaustive search", 2)
    table(doc, ["Ablation", "Observed change", "Design judgment"], [
        ["Remove Renderer ordering", f"{ck['root_alpha_beta']['renderer_order']['nodes']:,} → {ck['root_alpha_beta']['baseline']['nodes']:,} nodes", "Separate correctness from cost"],
        ["Remove certified reduction", f"{ck['root_alpha_beta']['renderer_gate']['nodes']:,} → {ck['root_alpha_beta']['baseline']['nodes']:,} nodes", "Proven phenotypes may reduce candidates"],
        ["Remove previous-board residue", "One forbidden action enters 768 complete states", "Residue is required for exact legality"],
        ["Use one board instead of full history", "Simple-ko judgment is retained", "Store only what the selected law needs"],
    ], [2.05, 2.2, 2.3], center_cols=(0,))

    doc.add_page_break()
    heading(doc, "4. WRRA Go 0.1: a playable algorithm", 1)
    heading(doc, "4.1 From exhaustive proof to bounded action", 2)
    paragraph(doc,
        "Full enumeration validates the state definition and rule implementation on 3×3 Go, but it cannot close the entire state space of 9×9 or larger boards. WRRA Go 0.1 retains the verified transition system, scores explicit structural properties of every legal candidate, and lets MCTS repeatedly compare candidates under a bounded computation budget. The same program runs controlled 5×5 matches and interactive 9×9 human-versus-engine games.")
    figure(doc, figures["architecture"], "Figure 6. The end-to-end decision path in WRRA Go 0.1.", 6.1)

    heading(doc, "4.2 Complete state and legal transition", 2)
    equation(doc, eq_state, 4.8)
    state_tbl = table(doc, ["Symbol", "Component", "Why it is needed"], [
        ["B", "Current Black/White occupancy", "Groups, liberties, capture, and scoring"],
        ["p", "Side to move", "Distinguishes actor and opponent"],
        ["ρ", "Previous-board array", "Rejects immediate simple-ko repetition"],
        ["c", "Consecutive-pass count", "Terminates after two passes"],
        ["n", "Move number", "Ledger and operational search boundary"],
    ], [0.8, 2.6, 3.2], center_cols=(0,))
    compact_table(state_tbl, 8.5, 68)
    equation(doc, eq_update, 5.8)
    paragraph(doc,
        "The placement function first checks vacancy, then removes adjacent opponent groups whose liberties fall to zero. It rejects the action if the newly placed player's group has zero liberties and no capture rescued it. It rejects simple ko when the resulting board equals ρ. A pass leaves the board unchanged while updating residue and the consecutive-pass counter. Two consecutive passes trigger area scoring.")

    heading(doc, "4.3 Eleven transparent Renderer channels", 2)
    paragraph(doc,
        "The Renderer uses eleven explicit channels rather than hidden neural-network parameters. The weights are fixed, not learned. The score never decides legality: the rule engine first closes the legal candidate set, after which Renderer scores influence search priors and rollout order. Every candidate's score and phenotype are written to the ledger.")
    equation(doc, eq_renderer, 3.8)
    weights = __import__("wrra_go_0_1").WRRARenderer.WEIGHTS
    rows = [
        ["capture", "Number of opponent stones captured immediately", f"{weights['capture']:+.2f}"],
        ["rescue", "Structural rescue of adjacent friendly stones in atari", f"{weights['rescue']:+.2f}"],
        ["atari", "Opponent stones left with one liberty", f"{weights['atari']:+.2f}"],
        ["connection", "Connection of two or more friendly groups", f"{weights['connection']:+.2f}"],
        ["cut pressure", "Simultaneous contact with two or more opponent groups", f"{weights['cut_pressure']:+.2f}"],
        ["liberties", "Liberties of the new group, capped at six", f"{weights['liberties']:+.2f}"],
        ["self atari", "One-liberty placement without capture", f"{weights['self_atari']:+.2f}"],
        ["eye fill", "Filling a friendly eye candidate without capture", f"{weights['eye_fill']:+.2f}"],
        ["area delta", "Immediate change in small enclosed regions", f"{weights['area_delta']:+.2f}"],
        ["position", "Board-size-dependent opening preference", f"{weights['position']:+.2f}"],
        ["pass readiness", "End when the opponent passed and the score is favorable", f"{weights['pass_readiness']:+.2f}"],
    ]
    renderer_tbl = table(doc, ["Channel", "Computation", "Weight"], rows, [1.45, 4.25, 0.9], center_cols=(0, 2))
    compact_table(renderer_tbl, 8.2, 64)

    heading(doc, "4.4 MCTS integration", 2)
    paragraph(doc,
        "MCTS is an established search algorithm. WRRA's contribution is not to rename it, but to provide a sufficient state, exact legal transition, explicit Renderer prior, guided rollout, phenotype labels, and an auditable ledger within one execution contract. Uniform MCTS with the same simulation count is used as a control so that the difference introduced by the Renderer can be measured directly.")
    equation(doc, eq_puct, 6.15)
    numbered(doc, [
        "Generate all legal placements and pass transitions from the current complete state.",
        "Normalize Renderer scores with a softmax to produce candidate priors.",
        "Descend the tree using mean value Q plus a prior-weighted exploration term.",
        "At a new node, run a bounded rollout biased toward high-ranked Renderer candidates.",
        "Backpropagate terminal or bounded area score from the root player's perspective.",
        "Select the most-visited action and record visits, value, prior, Renderer score, and phenotype.",
    ])

    heading(doc, "4.5 Running the program", 2)
    table(doc, ["Purpose", "Command", "Output"], [
        ["9×9 human vs engine", "python src/wrra_go_0_1.py play --size 9 --human B", "Interactive coordinate input"],
        ["Deterministic rule tests", "python src/wrra_go_0_1.py test", "Ko, capture, suicide, termination"],
        ["Paired benchmark", "python src/wrra_go_0_1.py benchmark", "Machine-readable JSON ledger"],
        ["9×9 self-play", "python src/wrra_go_0_1.py selfplay --size 9", "JSON decision ledger and SGF"],
    ], [1.55, 3.8, 1.65], center_cols=(0,))
    paragraph(doc,
        "Human moves use standard Go coordinates such as D4 and the word pass; column I is skipped. The default 72 simulations are an executable baseline. Larger budgets examine more candidates per move. The rule engine accepts 13×13 and 19×19 boards, while the quantitative tests in this release focus on 5×5 and 9×9.")

    heading(doc, "5. Execution validation", 1)
    heading(doc, "5.1 Deterministic rule tests", 2)
    test_labels = {
        "same_visible_board_witness": "Reproduce the same-visible-board witness pair",
        "simple_ko_blocks_repetition": "Simple ko blocks restoration of the previous board",
        "removing_residue_admits_repetition": "Removing residue admits the repetition",
        "same_board_different_residue_changes_legality": "Different residues change legality on the same board",
        "two_passes_terminate": "Two consecutive passes terminate the game",
        "capture_removes_surrounded_group": "Capture removes a surrounded group",
        "suicide_is_forbidden": "Suicide is forbidden",
        "area_scoring_is_deterministic": "Area scoring is deterministic",
        "renderer_does_not_claim_open_board": "Renderer does not mislabel an open region as territory",
        "coordinate_round_trip": "Coordinate conversion round trip",
    }
    table(doc, ["Test", "Result"], [[test_labels[key], "PASS" if value else "FAIL"] for key, value in tests.items()], [5.4, 1.2], center_cols=(1,))
    paragraph(doc,
        "The key regression test replays the shortest five-move witness found by Game 0.2 inside the engine's independent immutable state object. Both histories reach the same board with the same player to move, but their previous boards differ. White (0, 1) is legal in one state and rejected by simple ko in the other. This confirms that the state condition discovered by exhaustive analysis survives in the playable code.")

    heading(doc, "5.2 Paired-colour 5×5 benchmark", 2)
    paragraph(doc,
        f"WRRA MCTS and each control alternated Black and White. Each move used {benchmark['search']['simulations_per_move']} simulations. Uniform MCTS retained the same tree-search mechanism and computation budget but removed Renderer priors and guided rollouts. The random control selected one legal action uniformly.")
    figure(doc, figures["benchmark"], "Figure 7. WRRA MCTS against controls under identical rules and alternating colours; error bars are Wilson 95% intervals.", 5.7)
    table(doc, ["Control", "Games", "WRRA W–L", "Win rate", "Wilson 95% interval", "Mean moves"], [
        ["Uniform MCTS", uniform["games"], f"{uniform['wrra_wins']}–{uniform['wrra_losses']}", f"{100 * uniform['wrra_win_rate']:.1f}%", f"{100 * uniform['wilson_95_interval'][0]:.1f}–{100 * uniform['wilson_95_interval'][1]:.1f}%", f"{uniform['mean_move_count']:.1f}"],
        ["Random", random_control["games"], f"{random_control['wrra_wins']}–{random_control['wrra_losses']}", f"{100 * random_control['wrra_win_rate']:.1f}%", f"{100 * random_control['wilson_95_interval'][0]:.1f}–{100 * random_control['wilson_95_interval'][1]:.1f}%", f"{random_control['mean_move_count']:.1f}"],
    ], [1.2, 0.75, 1.1, 0.85, 1.65, 1.05], center_cols=(0, 1, 2, 3, 4, 5))
    paragraph(doc,
        "The justified conclusion is that the fixed Renderer produced an effective action-selection bias in this controlled sample and won more games than equal-budget uniform search. This sample does not establish superiority to professional engines or generalize playing strength to 19×19. Those are separate experiments that can be added without changing the execution contract.")

    heading(doc, "5.3 A complete 9×9 self-play record", 2)
    score = selfplay["score"]
    paragraph(doc,
        f"Two WRRA MCTS agents, each using {selfplay['moves'][0]['decision']['simulations']} simulations per move, played a 9×9 game that ended after {selfplay['move_count']} moves by {ending_name}. Black area was {score['black_area']}, White area was {score['white_area']}, and komi was {score['komi']}. The Black-margin score was {score['black_margin']:+.1f}; the winner was {winner_name}.")
    figure(doc, figures["final"], "Figure 8. Final position of the 9×9 WRRA self-play game; the complete SGF is included.", 4.9)
    figure(doc, figures["candidates"], "Figure 9. Candidate visits recorded for the first self-play move.", 5.9)
    first_candidates = selfplay["moves"][0]["decision"]["candidates"][:8]
    table(doc, ["Move", "Visits", "Mean value", "Prior", "Renderer score", "Phenotype"], [
        [item["action"], item["visits"], f"{item['value']:+.3f}", f"{item['prior']:.4f}", f"{item['renderer_score']:+.3f}", item["phenotype"]]
        for item in first_candidates
    ], [0.8, 0.75, 1.0, 1.0, 1.35, 1.35], center_cols=(0, 1, 2, 3, 4, 5))

    heading(doc, "5.4 Complete move list", 2)
    moves = selfplay["moves"]
    paired = []
    for i in range(0, len(moves), 2):
        paired.append([i // 2 + 1, moves[i]["action"], moves[i + 1]["action"] if i + 1 < len(moves) else ""])
    table(doc, ["Move no.", "Black", "White"], paired, [1.0, 2.8, 2.8], center_cols=(0, 1, 2))
    paragraph(doc,
        "The SGF stores the same sequence in standard coordinates. The JSON ledger stores each move's leading candidates, visits, mean value, prior, Renderer score, phenotype, and computation time. The selected action and its recorded rationale can therefore be re-examined independently.")

    heading(doc, "6. Scientific and engineering value", 1)
    heading(doc, "6.1 A connected chain of evidence", 2)
    numbered(doc, [
        "The same Core contract is applied to different games while preserving their different residue requirements. Integration means a shared test method, not erasure of domain differences.",
        "The work moves from constructed examples to complete reachability graphs, exact counterexamples, and value-preservation checks. Its explanations are therefore corrigible by computation.",
        "State correctness is separated from search efficiency. Removing residue changes legality; removing Renderer guidance can preserve value while increasing cost.",
        "When exhaustive search becomes impossible, the verified transition system is retained and coupled to bounded approximate search. Exact small-system proof is connected to larger-board action.",
        "Renderer channels, weights, candidate visits, and phenotypes are public. A move can be traced to explicit structural evidence rather than only a final output.",
        "The state–law–residue–Renderer–ledger interface is reusable for Omok, Go, Janggi, chess, and other deterministic games without modifying the frozen Core.",
    ])

    heading(doc, "6.2 Additional strengths revealed by the experiments", 2)
    table(doc, ["Strength", "Evidence in this release", "Meaning beyond games"], [
        ["Automatic state-aliasing detection", "752 residue-dependent visible-state classes", "Find different permitted actions behind the same observation"],
        ["Proof-carrying reduction", "Zero Connect-K value mismatches", "Use local phenotypes as certified computation gates"],
        ["Correctness/cost separation", "Residue and Renderer ablations", "Design memory and computation budget independently"],
        ["Scale transition", "3×3 exact validation to 9×9 MCTS", "Connect exhaustive tests to bounded operation"],
        ["Explainable action", "Eleven channels and per-candidate ledger", "Reinspect why an action was selected"],
        ["Core invariance", "No Core modification across 0.1, 0.2, and Go 0.1", "Extend domains while preserving the upper contract"],
    ], [1.65, 2.25, 2.35], center_cols=(0,))
    paragraph(doc,
        "The order of validation matters. First establish rule correctness, then state sufficiency, then lossless reduction, and only then evaluate bounded-search performance. The same pattern can connect small exact models with operational systems in power-grid analysis, biological regulation, and agent behavior, where total-state enumeration is unavailable.")

    heading(doc, "6.3 What is established and what remains open", 2)
    table(doc, ["Established in this release", "Next extension"], [
        ["Legal actions and transitions under simple ko", "Compressed residue for positional superko"],
        ["5×5 controlled matches and 9×9 execution", "Multi-seed 9×9 tournaments and timed 19×19 play"],
        ["Fixed transparent Renderer channels", "Weight ablation and calibrated optimization"],
        ["Executable integration with MCTS", "Rated GTP matches against external engines"],
        ["Area score, SGF, and JSON ledgers", "Dead-stone handling and separate Chinese/Japanese profiles"],
    ], [3.3, 3.3])
    paragraph(doc,
        "This table is not a retreat from the achieved result. It fixes the input and output of the next experiments. Version 1.0 is already a standalone program that a person can play; stronger tournament performance is a measurable extension on the same architecture.")

    doc.add_page_break()
    heading(doc, "7. Reproducibility and release", 1)
    heading(doc, "7.1 File lineage and SHA-256 manifest", 2)
    manifest = [
        ["wrra_game_0_1.py", "Constructive Omok and Go analysis", file_hash(ROOT / "wrra_game_0_1.py")],
        [R01_PATH.name, "Game 0.1 result ledger", file_hash(R01_PATH)],
        ["wrra_game_0_2.py", "Connect-K and 3×3 Go exhaustive analysis", file_hash(ROOT / "wrra_game_0_2.py")],
        [R02_PATH.name, "Game 0.2 result ledger", file_hash(R02_PATH)],
        ["wrra_go_0_1.py", "Playable engine and controlled evaluation", file_hash(ROOT / "wrra_go_0_1.py")],
        [BENCH_PATH.name, "Paired-colour benchmark", file_hash(BENCH_PATH)],
        [TEST_PATH.name, "Deterministic rule regression tests", file_hash(TEST_PATH)],
        [SELFPLAY_PATH.name, "Complete 9×9 decision ledger", file_hash(SELFPLAY_PATH)],
        [SELFPLAY_PATH.with_suffix(".sgf").name, "9×9 self-play SGF", file_hash(SELFPLAY_PATH.with_suffix(".sgf"))],
    ]
    manifest_tbl = table(doc, ["File", "Role", "SHA-256"], manifest, [2.25, 1.65, 2.95], center_cols=(0,))
    compact_table(manifest_tbl, 7.35, 54)

    heading(doc, "7.2 Reproduction sequence", 2)
    numbered(doc, [
        "Run python src/wrra_go_0_1.py test and confirm that all ten rule tests are true.",
        "Run python src/wrra_game_0_2.py and confirm 6,036,001 Connect-K states and zero value mismatches.",
        "In the same ledger, confirm 132,161 complete 3×3 Go states and 752 residue-dependent visible-state classes.",
        "Run python src/wrra_go_0_1.py benchmark --size 5 --paired-games 8 --simulations 48.",
        "Run python src/wrra_go_0_1.py selfplay --size 9 --simulations 24 to create JSON and SGF outputs.",
        "Start a human game with python src/wrra_go_0_1.py play --size 9 --human B.",
    ])
    paragraph(doc,
        f"The recorded benchmark runtime is {benchmark['elapsed_seconds']:.2f} seconds and will vary by environment. State counts, legality tests, fixed seeds, and recorded outcomes are reproducible under the same Python behavior and inputs. The archive includes the exhaustive 0.2 ledger so that its results can be inspected without repeating the full enumeration.")

    heading(doc, "7.3 Recommended repository and Zenodo metadata", 2)
    table(doc, ["Field", "Value"], [
        ["Title", "WRRA Game 1.0: Minimal Sufficient State, Exhaustive Validation, and a Playable Go Engine"],
        ["Subtitle", "From Constructive Omok and Go Analysis to WRRA Go 0.1"],
        ["Creator", "Wonsik Choi"],
        ["Contact", "janefather@gmail.com"],
        ["Resource type", "Software and technical report"],
        ["Language", "English; Korean companion report included"],
        ["Version", "1.0"],
        ["Keywords", "WRRA, Go, Baduk, Omok, Connect K, MCTS, minimal sufficient state, residue, Renderer, exhaustive search, explainable game AI, complex systems"],
        ["Related identifier", "WRRA Core 1.0 — https://doi.org/10.5281/zenodo.22650956"],
        ["License", "Reports, documentation, and data: CC BY 4.0; source code: MIT"],
    ], [1.45, 5.15], center_cols=(0,))

    heading(doc, "Release description", 3)
    paragraph(doc,
        "This release integrates the WRRA Game research program from constructive game analysis to exhaustive finite-state validation and a playable Go engine. Game 0.1 identifies an Omok forced-win phenotype and a simple-ko residue counterexample. Game 0.2 exhaustively enumerates 6,036,001 reachable Connect-K states and 132,161 reachable 3×3 Go states, finding zero minimax-value mismatches for a certified Renderer reduction and 752 visible-state classes whose legal actions depend on previous-board residue. WRRA Go 0.1 reuses the verified transition system in a playable 9×9 engine, combining a transparent eleven-channel Renderer with Monte Carlo Tree Search. The archive includes source code, machine-readable ledgers, deterministic rule tests, paired-control matches, and an SGF self-play record. The work evaluates rule-permitted continuations; it does not describe residue or search as prediction of a pre-existing future.")

    heading(doc, "7.4 Research lineage", 2)
    paragraph(doc, "WRRA Core 1.0: Frozen Domain-Agnostic Execution Architecture. DOI: 10.5281/zenodo.22650956.")
    paragraph(doc, "WRRA Game 0.1: Constructive complexity in Omok and Go. 16 September 2026.")
    paragraph(doc, "WRRA Game 0.2: Exhaustive Connect-K validation and residue sufficiency in Go. 17 September 2026.")
    paragraph(doc, "WRRA Go 0.1: The playable engine included in this report. 17 September 2026.")

    heading(doc, "Conclusion", 1)
    paragraph(doc,
        "This work does not stop at the statement that simple rules can create complex games. In Connect K it tests, over every reachable state, which Renderer phenotypes can act as certified computation reductions without changing value. In Go it identifies, through exhaustive counterexamples, which residue must enter the state for exact legality. It then places the same transition machinery in a playable 9×9 agent that selects moves and records both SGF and candidate-level ledgers.")
    paragraph(doc,
        "The central achievement of WRRA Game 1.0 is therefore a single reproducible execution system: preserve rule correctness with a minimal sufficient state, expose computationally relevant structure with a transparent Renderer, and select actual actions through bounded search.")

    props = doc.core_properties
    props.title = "WRRA Game 1.0: Minimal Sufficient State for Complex Games and a Playable Go Engine"
    props.subject = "Constructive analysis, exhaustive validation, and a playable Go engine"
    props.author = "Wonsik Choi"
    props.keywords = "WRRA, Go, Baduk, Omok, Connect K, MCTS, minimal sufficient state, residue, renderer, exhaustive search"
    props.comments = "WRRA Core 1.0 frozen; English integrated release"
    doc.save(DOCX_PATH)
    print(DOCX_PATH)


if __name__ == "__main__":
    build()
